exports.currencyList = [
  {
    currency_symbol: 'Rs. ',
    currency_position: 'before',
    decimal_sep: '.',
    thousand_sep: ',',
    cent_precision: 2,
    zero_format: true,
    currency_name: 'Pakistani Rupees',
    currency_code: 'PKR',
    enabled: true,
  },
  {
    currency_symbol: '$',
    currency_position: 'before',
    decimal_sep: '.',
    thousand_sep: ',',
    cent_precision: 2,
    zero_format: true,
    currency_name: 'US Dollar',
    currency_code: 'USD',
    enabled: true,
  },
  {
    currency_symbol: '€',
    currency_position: 'after',
    decimal_sep: '.',
    thousand_sep: ' ',
    cent_precision: 2,
    zero_format: true,
    currency_name: 'Euro',
    currency_code: 'EUR',
    enabled: true,
  },
];
