const mongoose = require('mongoose');
const Scenario = require('../src/models/appModels/Scenario'); // Adjust path based on your project structure

const uri = 'mongodb://localhost:27017/yourDatabase'; // Replace with your MongoDB URI
require('dotenv').config({ path: '.env' });
require('dotenv').config({ path: '.env.local' });
async function createScenariosCollection() {
  try {
    await mongoose.connect(process.env.DATABASE);
    console.log('Connected to MongoDB');

    // Optional: Clear existing scenarios (uncomment to reset the collection)
    // await Scenario.deleteMany({});

    const scenarios = [
      {
        id: '1',
        scenarioId: 'SN001',
        description: 'Sale of Standard Rate Goods to Registered Buyers',
        hscode_id: '0101.2100',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: '',
        sroItemSerialNo: '',
        saleType: 'Goods at standard rate (default)',
        rate: '18%',
      },
      {
        id: '2',
        scenarioId: 'SN002',
        description: 'Sale of Standard Rate Goods to Unregistered Buyers',
        hscode_id: '0101.2100',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: '',
        sroItemSerialNo: '',
        saleType: 'Goods at standard rate (default)',
        rate: '18%',
      },
      {
        id: '3',
        scenarioId: 'SN003',
        description: 'Sale of Steel (Melted and Re-Rolled) (Billets, Ingots)',
        hscode_id: '7214.1010',
        uom_id: 'MT',
        sroScheduleNo: '',
        sroItemSerialNo: '',
        saleType: 'Steel melting and re-rolling',
        rate: '18%',
      },
      {
        id: '4',
        scenarioId: 'SN004',
        description: 'Sale of Steel Scrap by Ship Breakers',
        hscode_id: '7214.1010',
        uom_id: 'MT',
        sroScheduleNo: '',
        sroItemSerialNo: '',
        saleType: 'Ship breaking',
        rate: '18%',
      },
      {
        id: '5',
        scenarioId: 'SN005',
        description: 'Sales of Reduced Rate Goods (Eighth Schedule)',
        hscode_id: '0102.2930',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: 'EIGHTH SCHEDULE Table 1',
        sroItemSerialNo: '',
        saleType: 'Goods at Reduced Rate',
        rate: '1%',
      },
      {
        id: '6',
        scenarioId: 'SN006',
        description: 'Sale of Exempt Goods (Sixth Schedule)',
        hscode_id: '0102.2930',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: '6th Schd Table I',
        sroItemSerialNo: '82',
        saleType: 'Exempt goods',
        rate: 'exempt',
      },
      {
        id: '7',
        scenarioId: 'SN007',
        description: 'Sale Of Zero-Rated Goods (Fifth Schedule)',
        hscode_id: '0102.2930',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: '6th Schd Table I',
        sroItemSerialNo: '100',
        saleType: 'Goods at zero-rate',
        rate: '0%',
      },
      {
        id: '8',
        scenarioId: 'SN008',
        description: 'Sale of 3rd Schedule Goods',
        hscode_id: '0101.2100',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: '',
        sroItemSerialNo: '',
        saleType: '3rd Schedule Goods',
        rate: '18%',
      },
      {
        id: '9',
        scenarioId: 'SN009',
        description: 'Purchase From Registered Cotton Ginners',
        hscode_id: '0101.2100',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: '',
        sroItemSerialNo: '',
        saleType: 'Cotton ginners',
        rate: '18%',
      },
      {
        id: '10',
        scenarioId: 'SN010',
        description: 'Sale Of Telecom Services by Mobile Operators',
        hscode_id: '7214.9990',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: '',
        sroItemSerialNo: '',
        saleType: 'Telecommunication services',
        rate: '17%',
      },
      {
        id: '11',
        scenarioId: 'SN011',
        description: 'Sale of Steel through Toll Manufacturing (Billets, Ingots)',
        hscode_id: '7214.9990',
        uom_id: 'MT',
        sroScheduleNo: '',
        sroItemSerialNo: '',
        saleType: 'Toll Manufacturing',
        rate: '18%',
      },
      {
        id: '12',
        scenarioId: 'SN012',
        description: 'Sale Of Petroleum Products',
        hscode_id: '0101.2100',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: '1450(I)/2021',
        sroItemSerialNo: '4',
        saleType: 'Petroleum Products',
        rate: '1.43%',
      },
      {
        id: '13',
        scenarioId: 'SN013',
        description: 'Sale Of Electricity to Retailers',
        hscode_id: '0101.2100',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: '1450(I)/2021',
        sroItemSerialNo: '4',
        saleType: 'Electricity Supply to Retailers',
        rate: '5%',
      },
      {
        id: '14',
        scenarioId: 'SN014',
        description: 'Sale of Gas to CNG Stations',
        hscode_id: '0101.2100',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: '',
        sroItemSerialNo: '',
        saleType: 'Gas to CNG stations',
        rate: '18%',
      },
      {
        id: '15',
        scenarioId: 'SN015',
        description: 'Sale of Mobile Phones',
        hscode_id: '0101.2100',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: 'NINTH SCHEDULE',
        sroItemSerialNo: '1(A)',
        saleType: 'Mobile Phones',
        rate: '18%',
      },
      {
        id: '16',
        scenarioId: 'SN016',
        description: 'Processing / Conversion of Goods',
        hscode_id: '0101.2100',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: '',
        sroItemSerialNo: '',
        saleType: 'Processing/Conversion of Goods',
        rate: '5%',
      },
      {
        id: '17',
        scenarioId: 'SN017',
        description: 'Sale of Goods Where FED Is Charged in ST Mode',
        hscode_id: '0101.2100',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: '',
        sroItemSerialNo: '',
        saleType: 'Goods (FED in ST Mode)',
        rate: '8%',
      },
      {
        id: '18',
        scenarioId: 'SN018',
        description: 'Sale Of Services Where FED Is Charged in ST Mode',
        hscode_id: '0101.2100',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: '',
        sroItemSerialNo: '',
        saleType: 'Services (FED in ST Mode)',
        rate: '8%',
      },
      {
        id: '19',
        scenarioId: 'SN019',
        description: 'Sale of Services (as per ICT Ordinance)',
        hscode_id: '0101.2900',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: 'ICTO TABLE I',
        sroItemSerialNo: '1(ii)(ii)(a',
        saleType: 'Services',
        rate: '5%',
      },
      {
        id: '20',
        scenarioId: 'SN020',
        description: 'Sale of Electric Vehicles',
        hscode_id: '0101.2900',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: '6th Schd Table III',
        sroItemSerialNo: '20',
        saleType: 'Electric Vehicle',
        rate: '1%',
      },
      {
        id: '21',
        scenarioId: 'SN021',
        description: 'Sale of Cement /Concrete Block',
        hscode_id: '0101.2100',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: '',
        sroItemSerialNo: '',
        saleType: 'Cement /Concrete Block',
        rate: 'Rs.3 per unit',
      },
      {
        id: '22',
        scenarioId: 'SN022',
        description: 'Sale of Potassium Chlorate',
        hscode_id: '3104.2000',
        uom_id: 'KG',
        sroScheduleNo: 'EIGHTH SCHEDULE Table 1',
        sroItemSerialNo: '56',
        saleType: 'Potassium Chlorate',
        rate: '18% + Rs.60/kg',
      },
      {
        id: '23',
        scenarioId: 'SN023',
        description: 'Sale of CNG',
        hscode_id: '0101.2100',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: '581(1)/2024',
        sroItemSerialNo: 'Region-I',
        saleType: 'CNG Sales',
        rate: 'Rs.200/unit',
      },
      {
        id: '24',
        scenarioId: 'SN024',
        description: 'Sale Of Goods Listed in SRO 297(1)/2023',
        hscode_id: '0101.2100',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: '297(I)/2023-Table-I',
        sroItemSerialNo: '12',
        saleType: 'Goods as per SRO.297(I)/2023',
        rate: '25%',
      },
      {
        id: '25',
        scenarioId: 'SN025',
        description: 'Drugs Sold at Fixed ST Rate Under Serial 81 Of Eighth Schedule',
        hscode_id: '0101.2100',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: 'EIGHTH SCHEDULE Table 1',
        sroItemSerialNo: '81',
        saleType: 'Non-Adjustable Supplies',
        rate: '0%',
      },


      {
        id: '26',
        scenarioId: 'SN026',
        description: 'Drugs Sold at Fixed ST Rate Under Serial 81 Of Eighth Schedule',
        hscode_id: '0101.2100',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: 'EIGHTH SCHEDULE Table 1',
        sroItemSerialNo: '81',
        saleType: 'Non-Adjustable Supplies',
        rate: '0%',
      },

      {
        id: '27',
        scenarioId: 'SN027',
        description: 'Drugs Sold at Fixed ST Rate Under Serial 81 Of Eighth Schedule',
        hscode_id: '0101.2100',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: 'EIGHTH SCHEDULE Table 1',
        sroItemSerialNo: '81',
        saleType: 'Non-Adjustable Supplies',
        rate: '0%',
      },


      {
        id: '28',
        scenarioId: 'SN028',
        description: 'Drugs Sold at Fixed ST Rate Under Serial 81 Of Eighth Schedule',
        hscode_id: '0101.2100',
        uom_id: 'Numbers, pieces, units',
        sroScheduleNo: 'EIGHTH SCHEDULE Table 1',
        sroItemSerialNo: '81',
        saleType: 'Non-Adjustable Supplies',
        rate: '0%',
      },


    ];

    const result = await Scenario.insertMany(scenarios);
    console.log(`Inserted ${result.length} scenarios`);
    console.log('Inserted scenarios:', result);
  } catch (error) {
    console.error('Error creating scenarios:', error);
  } finally {
    await mongoose.disconnect();
    console.log('MongoDB connection closed');
  }
}

createScenariosCollection();